/**
 * Generates src/formatters/phone-data.ts from libphonenumber-js metadata.
 *
 * Run: npx tsx scripts/generate-phone-data.ts
 */

import * as fs from 'fs';
import * as path from 'path';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const metadata = require('libphonenumber-js/metadata.min.json');

type MetadataFormat = [
  string, // pattern
  string, // template
  string[]?, // leading digits (progressive narrowing)
  string?, // national prefix formatting rule (e.g. "0$1")
  number?, // unknown
  string?, // intl format
];

type MetadataCountry = [
  string, // [0] calling code
  string, // [1] international prefix
  string, // [2] national number pattern
  number[], // [3] possible lengths
  MetadataFormat[]?, // [4] formats
  string?, // [5] national prefix (e.g. "0" or "1")
  // ... more fields we don't need
];

function countryCodeToFlag(code: string): string {
  return code
    .toUpperCase()
    .split('')
    .map((c) => String.fromCodePoint(c.charCodeAt(0) + 0x1f1a5))
    .join('');
}

function getCountryName(code: string): string {
  const displayNames = new Intl.DisplayNames(['en'], { type: 'region' });
  return displayNames.of(code) ?? code;
}

interface PhoneFormat {
  pattern: string;
  template: string;
  leadingDigits?: string;
}

interface CountryPhoneData {
  code: string;
  callingCode: string;
  formats: PhoneFormat[];
  nationalPrefix?: string;
  name: string;
  flag: string;
}

function processCountry(code: string, data: MetadataCountry): CountryPhoneData {
  const callingCode = data[0];
  const nationalPrefix = data[5];
  const rawFormats = Array.isArray(data[4]) ? data[4] : [];

  // A format's national prefix formatting rule (e.g. "0$1") means the national
  // prefix is part of how the number is displayed. We only carry the prefix for
  // countries that display it, so e.g. US/CA (prefix "1", no rule) keep their
  // bare-number formatting.
  let usesNationalPrefix = false;
  const formats: PhoneFormat[] = rawFormats.map((f) => {
    const leadingDigitsArray = f[2];
    // Use the last (most specific) leading digits pattern
    const leadingDigits = leadingDigitsArray
      ? leadingDigitsArray[leadingDigitsArray.length - 1]
      : undefined;

    if (f[3]) {
      usesNationalPrefix = true;
    }

    return {
      pattern: f[0],
      template: f[1],
      ...(leadingDigits != null ? { leadingDigits } : {}),
    };
  });

  return {
    code,
    callingCode,
    formats,
    ...(usesNationalPrefix &&
    typeof nationalPrefix === 'string' &&
    nationalPrefix.length > 0
      ? { nationalPrefix }
      : {}),
    name: getCountryName(code),
    flag: countryCodeToFlag(code),
  };
}

function generate(): string {
  const countries: Record<string, MetadataCountry> = metadata.countries;
  const callingCodes: Record<string, string[]> = metadata.country_calling_codes;
  const allData: Record<string, CountryPhoneData> = {};
  const list: CountryPhoneData[] = [];

  // First pass: process countries with their own formats
  for (const [code, data] of Object.entries(countries)) {
    const processed = processCountry(code, data as MetadataCountry);
    allData[code] = processed;
    list.push(processed);
  }

  // Second pass: resolve format inheritance for countries with data[4] === 0
  for (const [code, data] of Object.entries(countries)) {
    const d = data as MetadataCountry;
    if (!Array.isArray(d[4]) && allData[code]!.formats.length === 0) {
      // Find the main country for this calling code
      const callingCode = d[0];
      const mainCountries = callingCodes[callingCode];
      if (mainCountries) {
        const mainCountry = mainCountries[0]!;
        if (mainCountry !== code && allData[mainCountry]) {
          allData[code]!.formats = allData[mainCountry]!.formats;
          if (allData[mainCountry]!.nationalPrefix) {
            allData[code]!.nationalPrefix =
              allData[mainCountry]!.nationalPrefix;
          }
        }
      }
    }
  }

  // Sort by name
  list.sort((a, b) => a.name.localeCompare(b.name));

  // Build output
  const lines: string[] = [];

  lines.push('// Auto-generated by scripts/generate-phone-data.ts');
  lines.push('// Do not edit manually.');
  lines.push('');
  lines.push('export type PhoneFormat = {');
  lines.push('  pattern: string;');
  lines.push('  template: string;');
  lines.push('  leadingDigits?: string;');
  lines.push('};');
  lines.push('');
  lines.push('export type CountryPhoneData = {');
  lines.push('  code: string;');
  lines.push('  callingCode: string;');
  lines.push('  formats: PhoneFormat[];');
  lines.push('  nationalPrefix?: string;');
  lines.push('  name: string;');
  lines.push('  flag: string;');
  lines.push('};');
  lines.push('');

  // Generate the record
  lines.push(
    'export const COUNTRY_PHONE_DATA: Record<string, CountryPhoneData> = {',
  );
  for (const [code, data] of Object.entries(allData)) {
    const formatsStr = data.formats
      .map((f) => {
        const parts = [
          `pattern: ${JSON.stringify(f.pattern)}`,
          `template: ${JSON.stringify(f.template)}`,
        ];
        if (f.leadingDigits) {
          parts.push(`leadingDigits: ${JSON.stringify(f.leadingDigits)}`);
        }
        return `{ ${parts.join(', ')} }`;
      })
      .join(', ');

    const nationalPrefixStr = data.nationalPrefix
      ? `, nationalPrefix: ${JSON.stringify(data.nationalPrefix)}`
      : '';
    lines.push(
      `  ${JSON.stringify(code)}: { code: ${JSON.stringify(
        data.code,
      )}, callingCode: ${JSON.stringify(
        data.callingCode,
      )}, formats: [${formatsStr}]${nationalPrefixStr}, name: ${JSON.stringify(
        data.name,
      )}, flag: ${JSON.stringify(data.flag)} },`,
    );
  }
  lines.push('};');
  lines.push('');

  // Generate sorted list
  lines.push('export const COUNTRY_LIST: CountryPhoneData[] = [');
  for (const data of list) {
    lines.push(`  COUNTRY_PHONE_DATA[${JSON.stringify(data.code)}]!,`);
  }
  lines.push('];');
  lines.push('');

  // Calling code -> ISO country codes (primary country first). Used to detect
  // the country from a typed international calling code.
  lines.push(
    'export const COUNTRY_CALLING_CODES: Record<string, string[]> = {',
  );
  for (const [code, isos] of Object.entries(callingCodes)) {
    lines.push(`  ${JSON.stringify(code)}: ${JSON.stringify(isos)},`);
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

const output = generate();
const outPath = path.resolve(__dirname, '../src/formatters/phone-data.ts');
fs.writeFileSync(outPath, output, 'utf-8');
console.log(
  `Generated ${outPath} (${Object.keys(metadata.countries).length} countries)`,
);
